services:
  postgres:
    image: postgres:16-alpine
    command: -c 'max_connections=200'
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: masp_indexer_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "masp_indexer_local"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

  block-index:
    image: namada-masp-block-index
    build:
      context: .
      dockerfile: block-index/Dockerfile
    environment:
      COMETBFT_URL: ${COMETBFT_URL}
      DATABASE_URL: postgres://postgres:password@postgres:5432/masp_indexer_local
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: namada-masp-webserver
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:password@postgres:5432/masp_indexer_local
    depends_on:
      - crawler
  
  crawler:
    build:
      context: .
      dockerfile: chain/Dockerfile
    environment:
      COMETBFT_URL: ${COMETBFT_URL}
      DATABASE_URL: postgres://postgres:password@postgres:5432/masp_indexer_local
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres-data:
